/** Auto-generated stroke bulk data — do not edit by hand */
import type { StrokeEntry } from "./types";

export const STROKE_BULK: Record<string, StrokeEntry> = {
  "卓": { char: "卓", simplified: 8, traditional: 8, kangxi: 8 },
  "晓": { char: "晓", simplified: 10, traditional: 16, traditionalChar: "曉", kangxi: 16 },
  "曉": { char: "曉", simplified: 16, traditional: 16, kangxi: 16 },
  "婷": { char: "婷", simplified: 12, traditional: 12, kangxi: 12 },
  "王": { char: "王", simplified: 4, traditional: 4, kangxi: 4 },
  "李": { char: "李", simplified: 7, traditional: 7, kangxi: 7 },
  "张": { char: "张", simplified: 11, traditional: 11, kangxi: 11 },
  "劉": { char: "劉", simplified: 15, traditional: 15, kangxi: 15 },
  "刘": { char: "刘", simplified: 6, traditional: 15, traditionalChar: "劉", kangxi: 15 },
  "陈": { char: "陈", simplified: 7, traditional: 10, traditionalChar: "陳", kangxi: 10 },
  "陳": { char: "陳", simplified: 10, traditional: 10, kangxi: 10 },
  "杨": { char: "杨", simplified: 7, traditional: 13, traditionalChar: "楊", kangxi: 13 },
  "楊": { char: "楊", simplified: 13, traditional: 13, kangxi: 13 },
  "赵": { char: "赵", simplified: 9, traditional: 14, traditionalChar: "趙", kangxi: 14 },
  "趙": { char: "趙", simplified: 14, traditional: 14, kangxi: 14 },
  "黄": { char: "黄", simplified: 11, traditional: 12, traditionalChar: "黃", kangxi: 12 },
  "黃": { char: "黃", simplified: 12, traditional: 12, kangxi: 12 },
  "周": { char: "周", simplified: 8, traditional: 8, kangxi: 8 },
  "吴": { char: "吴", simplified: 7, traditional: 7, kangxi: 7 },
  "郑": { char: "郑", simplified: 8, traditional: 14, traditionalChar: "鄭", kangxi: 14 },
  "鄭": { char: "鄭", simplified: 14, traditional: 14, kangxi: 14 },
  "孙": { char: "孙", simplified: 6, traditional: 10, traditionalChar: "孫", kangxi: 10 },
  "孫": { char: "孫", simplified: 10, traditional: 10, kangxi: 10 },
  "胡": { char: "胡", simplified: 9, traditional: 9, kangxi: 9 },
  "朱": { char: "朱", simplified: 6, traditional: 6, kangxi: 6 },
  "高": { char: "高", simplified: 10, traditional: 10, kangxi: 10 },
  "林": { char: "林", simplified: 8, traditional: 8, kangxi: 8 },
  "何": { char: "何", simplified: 7, traditional: 7, kangxi: 7 },
  "郭": { char: "郭", simplified: 10, traditional: 11, traditionalChar: "郭", kangxi: 11 },
  "马": { char: "马", simplified: 3, traditional: 10, traditionalChar: "馬", kangxi: 10 },
  "馬": { char: "馬", simplified: 10, traditional: 10, kangxi: 10 },
  "罗": { char: "罗", simplified: 8, traditional: 19, traditionalChar: "羅", kangxi: 19 },
  "羅": { char: "羅", simplified: 19, traditional: 19, kangxi: 19 },
  "梁": { char: "梁", simplified: 11, traditional: 11, kangxi: 11 },
  "宋": { char: "宋", simplified: 7, traditional: 7, kangxi: 7 },
  "谢": { char: "谢", simplified: 12, traditional: 17, traditionalChar: "謝", kangxi: 17 },
  "謝": { char: "謝", simplified: 17, traditional: 17, kangxi: 17 },
  "韩": { char: "韩", simplified: 12, traditional: 17, traditionalChar: "韓", kangxi: 17 },
  "韓": { char: "韓", simplified: 17, traditional: 17, kangxi: 17 },
  "唐": { char: "唐", simplified: 10, traditional: 10, kangxi: 10 },
  "冯": { char: "冯", simplified: 5, traditional: 12, traditionalChar: "馮", kangxi: 12 },
  "馮": { char: "馮", simplified: 12, traditional: 12, kangxi: 12 },
  "于": { char: "于", simplified: 3, traditional: 3, kangxi: 3 },
  "董": { char: "董", simplified: 12, traditional: 12, kangxi: 12 },
  "萧": { char: "萧", simplified: 11, traditional: 16, kangxi: 16 },
  "蕭": { char: "蕭", simplified: 16, traditional: 16, kangxi: 16 },
  "程": { char: "程", simplified: 12, traditional: 12, kangxi: 12 },
  "曹": { char: "曹", simplified: 11, traditional: 11, kangxi: 11 },
  "袁": { char: "袁", simplified: 10, traditional: 10, kangxi: 10 },
  "邓": { char: "邓", simplified: 4, traditional: 14, traditionalChar: "鄧", kangxi: 14 },
  "鄧": { char: "鄧", simplified: 14, traditional: 14, kangxi: 14 },
  "许": { char: "许", simplified: 6, traditional: 11, traditionalChar: "許", kangxi: 11 },
  "許": { char: "許", simplified: 11, traditional: 11, kangxi: 11 },
  "傅": { char: "傅", simplified: 12, traditional: 12, kangxi: 12 },
  "沈": { char: "沈", simplified: 7, traditional: 7, kangxi: 7 },
  "曾": { char: "曾", simplified: 12, traditional: 12, kangxi: 12 },
  "彭": { char: "彭", simplified: 12, traditional: 12, kangxi: 12 },
  "吕": { char: "吕", simplified: 6, traditional: 6, kangxi: 6 },
  "苏": { char: "苏", simplified: 7, traditional: 19, kangxi: 19 },
  "蘇": { char: "蘇", simplified: 19, traditional: 19, kangxi: 19 },
  "卢": { char: "卢", simplified: 5, traditional: 16, traditionalChar: "盧", kangxi: 16 },
  "盧": { char: "盧", simplified: 16, traditional: 16, kangxi: 16 },
  "蒋": { char: "蒋", simplified: 12, traditional: 14, kangxi: 14 },
  "蔣": { char: "蔣", simplified: 14, traditional: 14, kangxi: 14 },
  "蔡": { char: "蔡", simplified: 14, traditional: 14, kangxi: 14 },
  "贾": { char: "贾", simplified: 10, traditional: 13, traditionalChar: "賈", kangxi: 13 },
  "賈": { char: "賈", simplified: 13, traditional: 13, kangxi: 13 },
  "丁": { char: "丁", simplified: 2, traditional: 2, kangxi: 2 },
  "魏": { char: "魏", simplified: 17, traditional: 17, kangxi: 17 },
  "薛": { char: "薛", simplified: 16, traditional: 16, kangxi: 16 },
  "叶": { char: "叶", simplified: 5, traditional: 12, traditionalChar: "葉", kangxi: 12 },
  "葉": { char: "葉", simplified: 12, traditional: 12, kangxi: 12 },
  "阎": { char: "阎", simplified: 11, traditional: 16, kangxi: 16 },
  "余": { char: "余", simplified: 7, traditional: 7, kangxi: 7 },
  "潘": { char: "潘", simplified: 15, traditional: 15, kangxi: 15 },
  "杜": { char: "杜", simplified: 7, traditional: 7, kangxi: 7 },
  "戴": { char: "戴", simplified: 17, traditional: 17, kangxi: 17 },
  "夏": { char: "夏", simplified: 10, traditional: 10, kangxi: 10 },
  "钟": { char: "钟", simplified: 9, traditional: 17, kangxi: 17 },
  "汪": { char: "汪", simplified: 7, traditional: 7, kangxi: 7 },
  "田": { char: "田", simplified: 5, traditional: 5, kangxi: 5 },
  "任": { char: "任", simplified: 6, traditional: 6, kangxi: 6 },
  "姜": { char: "姜", simplified: 9, traditional: 9, kangxi: 9 },
  "范": { char: "范", simplified: 8, traditional: 11, traditionalChar: "範", kangxi: 11 },
  "範": { char: "範", simplified: 11, traditional: 11, kangxi: 11 },
  "方": { char: "方", simplified: 4, traditional: 4, kangxi: 4 },
  "石": { char: "石", simplified: 5, traditional: 5, kangxi: 5 },
  "姚": { char: "姚", simplified: 9, traditional: 9, kangxi: 9 },
  "谭": { char: "谭", simplified: 14, traditional: 19, traditionalChar: "譚", kangxi: 19 },
  "譚": { char: "譚", simplified: 19, traditional: 19, kangxi: 19 },
  "廖": { char: "廖", simplified: 14, traditional: 14, kangxi: 14 },
  "邹": { char: "邹", simplified: 7, traditional: 12, traditionalChar: "鄒", kangxi: 12 },
  "熊": { char: "熊", simplified: 14, traditional: 14, kangxi: 14 },
  "金": { char: "金", simplified: 8, traditional: 8, kangxi: 8 },
  "陆": { char: "陆", simplified: 7, traditional: 11, traditionalChar: "陸", kangxi: 11 },
  "陸": { char: "陸", simplified: 11, traditional: 11, kangxi: 11 },
  "郝": { char: "郝", simplified: 9, traditional: 9, kangxi: 9 },
  "孔": { char: "孔", simplified: 4, traditional: 4, kangxi: 4 },
  "白": { char: "白", simplified: 5, traditional: 5, kangxi: 5 },
  "崔": { char: "崔", simplified: 11, traditional: 11, kangxi: 11 },
  "康": { char: "康", simplified: 11, traditional: 11, kangxi: 11 },
  "毛": { char: "毛", simplified: 4, traditional: 4, kangxi: 4 },
  "邱": { char: "邱", simplified: 7, traditional: 7, kangxi: 7 },
  "秦": { char: "秦", simplified: 10, traditional: 10, kangxi: 10 },
  "江": { char: "江", simplified: 6, traditional: 6, kangxi: 6 },
  "史": { char: "史", simplified: 5, traditional: 5, kangxi: 5 },
  "顾": { char: "顾", simplified: 10, traditional: 21, traditionalChar: "顧", kangxi: 21 },
  "顧": { char: "顧", simplified: 21, traditional: 21, kangxi: 21 },
  "侯": { char: "侯", simplified: 9, traditional: 9, kangxi: 9 },
  "邵": { char: "邵", simplified: 7, traditional: 7, kangxi: 7 },
  "孟": { char: "孟", simplified: 8, traditional: 8, kangxi: 8 },
  "龙": { char: "龙", simplified: 5, traditional: 16, traditionalChar: "龍", kangxi: 16 },
  "龍": { char: "龍", simplified: 16, traditional: 16, kangxi: 16 },
  "万": { char: "万", simplified: 3, traditional: 12, traditionalChar: "萬", kangxi: 12 },
  "萬": { char: "萬", simplified: 12, traditional: 12, kangxi: 12 },
  "段": { char: "段", simplified: 9, traditional: 9, kangxi: 9 },
  "雷": { char: "雷", simplified: 13, traditional: 13, kangxi: 13 },
  "钱": { char: "钱", simplified: 10, traditional: 16, traditionalChar: "錢", kangxi: 16 },
  "錢": { char: "錢", simplified: 16, traditional: 16, kangxi: 16 },
  "汤": { char: "汤", simplified: 6, traditional: 13, traditionalChar: "湯", kangxi: 13 },
  "湯": { char: "湯", simplified: 13, traditional: 13, kangxi: 13 },
  "尹": { char: "尹", simplified: 4, traditional: 4, kangxi: 4 },
  "黎": { char: "黎", simplified: 15, traditional: 15, kangxi: 15 },
  "易": { char: "易", simplified: 8, traditional: 8, kangxi: 8 },
  "常": { char: "常", simplified: 11, traditional: 11, kangxi: 11 },
  "武": { char: "武", simplified: 8, traditional: 8, kangxi: 8 },
  "乔": { char: "乔", simplified: 6, traditional: 12, kangxi: 12 },
  "喬": { char: "喬", simplified: 12, traditional: 12, kangxi: 12 },
  "贺": { char: "贺", simplified: 9, traditional: 12, traditionalChar: "賀", kangxi: 12 },
  "賀": { char: "賀", simplified: 12, traditional: 12, kangxi: 12 },
  "赖": { char: "赖", simplified: 13, traditional: 16, traditionalChar: "賴", kangxi: 16 },
  "賴": { char: "賴", simplified: 16, traditional: 16, kangxi: 16 },
  "龚": { char: "龚", simplified: 11, traditional: 22, traditionalChar: "龔", kangxi: 22 },
  "文": { char: "文", simplified: 4, traditional: 4, kangxi: 4 },
  "明": { char: "明", simplified: 8, traditional: 8, kangxi: 8 },
  "华": { char: "华", simplified: 6, traditional: 10, kangxi: 10 },
  "華": { char: "華", simplified: 10, traditional: 10, kangxi: 10 },
  "美": { char: "美", simplified: 9, traditional: 9, kangxi: 9 },
  "丽": { char: "丽", simplified: 7, traditional: 19, traditionalChar: "麗", kangxi: 19 },
  "麗": { char: "麗", simplified: 19, traditional: 19, kangxi: 19 },
  "静": { char: "静", simplified: 14, traditional: 16, traditionalChar: "靜", kangxi: 16 },
  "靜": { char: "靜", simplified: 16, traditional: 16, kangxi: 16 },
  "伟": { char: "伟", simplified: 6, traditional: 11, traditionalChar: "偉", kangxi: 11 },
  "偉": { char: "偉", simplified: 11, traditional: 11, kangxi: 11 },
  "强": { char: "强", simplified: 12, traditional: 11, kangxi: 11 },
  "強": { char: "強", simplified: 11, traditional: 11, kangxi: 11 },
  "芳": { char: "芳", simplified: 7, traditional: 7, kangxi: 7 },
  "娜": { char: "娜", simplified: 9, traditional: 9, kangxi: 9 },
  "敏": { char: "敏", simplified: 11, traditional: 11, kangxi: 11 },
  "磊": { char: "磊", simplified: 15, traditional: 15, kangxi: 15 },
  "军": { char: "军", simplified: 6, traditional: 9, traditionalChar: "軍", kangxi: 9 },
  "軍": { char: "軍", simplified: 9, traditional: 9, kangxi: 9 },
  "洋": { char: "洋", simplified: 9, traditional: 9, kangxi: 9 },
  "勇": { char: "勇", simplified: 9, traditional: 9, kangxi: 9 },
  "艳": { char: "艳", simplified: 10, traditional: 24, traditionalChar: "艷", kangxi: 24 },
  "杰": { char: "杰", simplified: 8, traditional: 12, traditionalChar: "傑", kangxi: 12 },
  "傑": { char: "傑", simplified: 12, traditional: 12, kangxi: 12 },
  "涛": { char: "涛", simplified: 10, traditional: 18, traditionalChar: "濤", kangxi: 18 },
  "濤": { char: "濤", simplified: 18, traditional: 18, kangxi: 18 },
  "超": { char: "超", simplified: 12, traditional: 12, kangxi: 12 },
  "秀": { char: "秀", simplified: 7, traditional: 7, kangxi: 7 },
  "英": { char: "英", simplified: 8, traditional: 8, kangxi: 8 },
  "慧": { char: "慧", simplified: 15, traditional: 15, kangxi: 15 },
  "雪": { char: "雪", simplified: 11, traditional: 11, kangxi: 11 },
  "梅": { char: "梅", simplified: 11, traditional: 11, kangxi: 11 },
  "兰": { char: "兰", simplified: 5, traditional: 20, traditionalChar: "蘭", kangxi: 20 },
  "蘭": { char: "蘭", simplified: 20, traditional: 20, kangxi: 20 },
  "红": { char: "红", simplified: 6, traditional: 9, traditionalChar: "紅", kangxi: 9 },
  "紅": { char: "紅", simplified: 9, traditional: 9, kangxi: 9 },
  "云": { char: "云", simplified: 4, traditional: 12, kangxi: 12 },
  "雲": { char: "雲", simplified: 12, traditional: 12, kangxi: 12 },
  "霞": { char: "霞", simplified: 17, traditional: 17, kangxi: 17 },
  "春": { char: "春", simplified: 9, traditional: 9, kangxi: 9 },
  "秋": { char: "秋", simplified: 9, traditional: 9, kangxi: 9 },
  "冬": { char: "冬", simplified: 5, traditional: 5, kangxi: 5 },
  "天": { char: "天", simplified: 4, traditional: 4, kangxi: 4 },
  "地": { char: "地", simplified: 6, traditional: 6, kangxi: 6 },
  "人": { char: "人", simplified: 2, traditional: 2, kangxi: 2 },
  "心": { char: "心", simplified: 4, traditional: 4, kangxi: 4 },
  "志": { char: "志", simplified: 7, traditional: 7, kangxi: 7 },
  "成": { char: "成", simplified: 6, traditional: 6, kangxi: 6 },
  "建": { char: "建", simplified: 8, traditional: 8, kangxi: 8 },
  "国": { char: "国", simplified: 8, traditional: 11, traditionalChar: "國", kangxi: 11 },
  "國": { char: "國", simplified: 11, traditional: 11, kangxi: 11 },
  "家": { char: "家", simplified: 10, traditional: 10, kangxi: 10 },
  "安": { char: "安", simplified: 6, traditional: 6, kangxi: 6 },
  "乐": { char: "乐", simplified: 5, traditional: 15, kangxi: 15 },
  "樂": { char: "樂", simplified: 15, traditional: 15, kangxi: 15 },
  "福": { char: "福", simplified: 13, traditional: 13, kangxi: 13 },
  "寿": { char: "寿", simplified: 7, traditional: 14, kangxi: 14 },
  "喜": { char: "喜", simplified: 12, traditional: 12, kangxi: 12 },
  "德": { char: "德", simplified: 15, traditional: 15, kangxi: 15 },
  "仁": { char: "仁", simplified: 4, traditional: 4, kangxi: 4 },
  "义": { char: "义", simplified: 3, traditional: 13, traditionalChar: "義", kangxi: 13 },
  "義": { char: "義", simplified: 13, traditional: 13, kangxi: 13 },
  "礼": { char: "礼", simplified: 5, traditional: 18, traditionalChar: "禮", kangxi: 18 },
  "禮": { char: "禮", simplified: 18, traditional: 18, kangxi: 18 },
  "智": { char: "智", simplified: 12, traditional: 12, kangxi: 12 },
  "信": { char: "信", simplified: 9, traditional: 9, kangxi: 9 },
  "小": { char: "小", simplified: 3, traditional: 3, kangxi: 3 },
  "大": { char: "大", simplified: 3, traditional: 3, kangxi: 3 },
  "中": { char: "中", simplified: 4, traditional: 4, kangxi: 4 },
  "正": { char: "正", simplified: 5, traditional: 5, kangxi: 5 },
  "平": { char: "平", simplified: 5, traditional: 5, kangxi: 5 },
  "和": { char: "和", simplified: 8, traditional: 8, kangxi: 8 },
  "新": { char: "新", simplified: 13, traditional: 13, kangxi: 13 },
  "永": { char: "永", simplified: 5, traditional: 5, kangxi: 5 },
  "世": { char: "世", simplified: 5, traditional: 5, kangxi: 5 },
  "子": { char: "子", simplified: 3, traditional: 3, kangxi: 3 },
  "一": { char: "一", simplified: 1, traditional: 1, kangxi: 1 },
  "二": { char: "二", simplified: 2, traditional: 2, kangxi: 2 },
  "三": { char: "三", simplified: 3, traditional: 3, kangxi: 3 },
  "四": { char: "四", simplified: 5, traditional: 5, kangxi: 5 },
  "五": { char: "五", simplified: 4, traditional: 4, kangxi: 4 },
  "六": { char: "六", simplified: 4, traditional: 4, kangxi: 4 },
  "七": { char: "七", simplified: 2, traditional: 2, kangxi: 2 },
  "八": { char: "八", simplified: 2, traditional: 2, kangxi: 2 },
  "九": { char: "九", simplified: 2, traditional: 2, kangxi: 2 },
  "十": { char: "十", simplified: 2, traditional: 2, kangxi: 2 },
  "褚": { char: "褚", simplified: 13, traditional: 13, kangxi: 13 },
  "卫": { char: "卫", simplified: 3, traditional: 11, traditionalChar: "衛", kangxi: 11 },
  "衛": { char: "衛", simplified: 11, traditional: 11, kangxi: 11 },
  "尤": { char: "尤", simplified: 4, traditional: 4, kangxi: 4 },
  "施": { char: "施", simplified: 9, traditional: 9, kangxi: 9 },
  "严": { char: "严", simplified: 7, traditional: 19, traditionalChar: "嚴", kangxi: 19 },
  "嚴": { char: "嚴", simplified: 19, traditional: 19, kangxi: 19 },
  "陶": { char: "陶", simplified: 10, traditional: 10, kangxi: 10 },
  "戚": { char: "戚", simplified: 11, traditional: 11, kangxi: 11 },
  "喻": { char: "喻", simplified: 12, traditional: 12, kangxi: 12 },
  "柏": { char: "柏", simplified: 9, traditional: 9, kangxi: 9 },
  "水": { char: "水", simplified: 4, traditional: 4, kangxi: 4 },
  "窦": { char: "窦", simplified: 13, traditional: 13, kangxi: 13 },
  "章": { char: "章", simplified: 11, traditional: 11, kangxi: 11 },
  "葛": { char: "葛", simplified: 12, traditional: 12, kangxi: 12 },
  "奚": { char: "奚", simplified: 10, traditional: 10, kangxi: 10 },
  "郎": { char: "郎", simplified: 8, traditional: 9, traditionalChar: "郎", kangxi: 9 },
  "鲁": { char: "鲁", simplified: 12, traditional: 15, traditionalChar: "魯", kangxi: 15 },
  "魯": { char: "魯", simplified: 15, traditional: 15, kangxi: 15 },
  "韦": { char: "韦", simplified: 4, traditional: 9, traditionalChar: "韋", kangxi: 9 },
  "韋": { char: "韋", simplified: 9, traditional: 9, kangxi: 9 },
  "昌": { char: "昌", simplified: 8, traditional: 8, kangxi: 8 },
  "苗": { char: "苗", simplified: 8, traditional: 8, kangxi: 8 },
  "凤": { char: "凤", simplified: 4, traditional: 14, traditionalChar: "鳳", kangxi: 14 },
  "鳳": { char: "鳳", simplified: 14, traditional: 14, kangxi: 14 },
  "花": { char: "花", simplified: 7, traditional: 7, kangxi: 7 },
  "俞": { char: "俞", simplified: 9, traditional: 9, kangxi: 9 },
  "柳": { char: "柳", simplified: 9, traditional: 9, kangxi: 9 },
  "鲍": { char: "鲍", simplified: 8, traditional: 16, traditionalChar: "鮑", kangxi: 16 },
  "鮑": { char: "鮑", simplified: 16, traditional: 16, kangxi: 16 },
  "费": { char: "费", simplified: 9, traditional: 12, traditionalChar: "費", kangxi: 12 },
  "費": { char: "費", simplified: 12, traditional: 12, kangxi: 12 },
  "廉": { char: "廉", simplified: 13, traditional: 13, kangxi: 13 },
  "岑": { char: "岑", simplified: 7, traditional: 7, kangxi: 7 },
  "倪": { char: "倪", simplified: 10, traditional: 10, kangxi: 10 },
  "滕": { char: "滕", simplified: 15, traditional: 15, kangxi: 15 },
  "殷": { char: "殷", simplified: 10, traditional: 10, kangxi: 10 },
  "毕": { char: "毕", simplified: 6, traditional: 11, traditionalChar: "畢", kangxi: 11 },
  "畢": { char: "畢", simplified: 11, traditional: 11, kangxi: 11 },
  "邬": { char: "邬", simplified: 6, traditional: 13, kangxi: 13 },
  "时": { char: "时", simplified: 7, traditional: 10, traditionalChar: "時", kangxi: 10 },
  "時": { char: "時", simplified: 10, traditional: 10, kangxi: 10 },
  "皮": { char: "皮", simplified: 5, traditional: 5, kangxi: 5 },
  "卞": { char: "卞", simplified: 4, traditional: 4, kangxi: 4 },
  "齐": { char: "齐", simplified: 6, traditional: 14, traditionalChar: "齊", kangxi: 14 },
  "齊": { char: "齊", simplified: 14, traditional: 14, kangxi: 14 },
  "伍": { char: "伍", simplified: 6, traditional: 6, kangxi: 6 },
  "元": { char: "元", simplified: 4, traditional: 4, kangxi: 4 },
  "卜": { char: "卜", simplified: 2, traditional: 2, kangxi: 2 },
  "穆": { char: "穆", simplified: 16, traditional: 16, kangxi: 16 },
  "祁": { char: "祁", simplified: 6, traditional: 6, kangxi: 6 },
  "禹": { char: "禹", simplified: 9, traditional: 9, kangxi: 9 },
  "狄": { char: "狄", simplified: 7, traditional: 7, kangxi: 7 },
  "米": { char: "米", simplified: 6, traditional: 6, kangxi: 6 },
  "贝": { char: "贝", simplified: 4, traditional: 7, traditionalChar: "貝", kangxi: 7 },
  "貝": { char: "貝", simplified: 7, traditional: 7, kangxi: 7 },
  "臧": { char: "臧", simplified: 14, traditional: 14, kangxi: 14 },
  "计": { char: "计", simplified: 4, traditional: 9, traditionalChar: "計", kangxi: 9 },
  "計": { char: "計", simplified: 9, traditional: 9, kangxi: 9 },
  "伏": { char: "伏", simplified: 6, traditional: 6, kangxi: 6 },
  "谈": { char: "谈", simplified: 10, traditional: 15, traditionalChar: "談", kangxi: 15 },
  "談": { char: "談", simplified: 15, traditional: 15, kangxi: 15 },
  "庞": { char: "庞", simplified: 8, traditional: 19, traditionalChar: "龐", kangxi: 19 },
  "龐": { char: "龐", simplified: 19, traditional: 19, kangxi: 19 },
  "纪": { char: "纪", simplified: 6, traditional: 9, traditionalChar: "紀", kangxi: 9 },
  "紀": { char: "紀", simplified: 9, traditional: 9, kangxi: 9 },
  "舒": { char: "舒", simplified: 12, traditional: 12, kangxi: 12 },
  "屈": { char: "屈", simplified: 8, traditional: 8, kangxi: 8 },
  "项": { char: "项", simplified: 9, traditional: 12, traditionalChar: "項", kangxi: 12 },
  "項": { char: "項", simplified: 12, traditional: 12, kangxi: 12 },
  "祝": { char: "祝", simplified: 9, traditional: 9, kangxi: 9 },
  "阮": { char: "阮", simplified: 6, traditional: 6, kangxi: 6 },
  "蓝": { char: "蓝", simplified: 13, traditional: 20, traditionalChar: "藍", kangxi: 20 },
  "藍": { char: "藍", simplified: 20, traditional: 20, kangxi: 20 },
  "闵": { char: "闵", simplified: 7, traditional: 12, traditionalChar: "閔", kangxi: 12 },
  "閔": { char: "閔", simplified: 12, traditional: 12, kangxi: 12 },
  "席": { char: "席", simplified: 10, traditional: 10, kangxi: 10 },
  "季": { char: "季", simplified: 8, traditional: 8, kangxi: 8 },
  "麻": { char: "麻", simplified: 11, traditional: 11, kangxi: 11 },
  "路": { char: "路", simplified: 13, traditional: 13, kangxi: 13 },
  "娄": { char: "娄", simplified: 9, traditional: 11, traditionalChar: "婁", kangxi: 11 },
  "婁": { char: "婁", simplified: 11, traditional: 11, kangxi: 11 },
  "危": { char: "危", simplified: 6, traditional: 6, kangxi: 6 },
  "童": { char: "童", simplified: 12, traditional: 12, kangxi: 12 },
  "颜": { char: "颜", simplified: 15, traditional: 18, traditionalChar: "顏", kangxi: 18 },
  "顏": { char: "顏", simplified: 18, traditional: 18, kangxi: 18 },
  "盛": { char: "盛", simplified: 11, traditional: 11, kangxi: 11 },
  "刁": { char: "刁", simplified: 2, traditional: 2, kangxi: 2 },
  "骆": { char: "骆", simplified: 9, traditional: 14, traditionalChar: "駱", kangxi: 14 },
  "駱": { char: "駱", simplified: 14, traditional: 14, kangxi: 14 },
  "凌": { char: "凌", simplified: 10, traditional: 10, kangxi: 10 },
  "霍": { char: "霍", simplified: 16, traditional: 16, kangxi: 16 },
  "虞": { char: "虞", simplified: 13, traditional: 13, kangxi: 13 },
  "支": { char: "支", simplified: 4, traditional: 4, kangxi: 4 },
  "柯": { char: "柯", simplified: 9, traditional: 9, kangxi: 9 },
  "昝": { char: "昝", simplified: 9, traditional: 9, kangxi: 9 },
  "管": { char: "管", simplified: 14, traditional: 14, kangxi: 14 },
  "莫": { char: "莫", simplified: 10, traditional: 10, kangxi: 10 },
  "经": { char: "经", simplified: 8, traditional: 13, traditionalChar: "經", kangxi: 13 },
  "經": { char: "經", simplified: 13, traditional: 13, kangxi: 13 },
  "房": { char: "房", simplified: 8, traditional: 8, kangxi: 8 },
  "裘": { char: "裘", simplified: 13, traditional: 13, kangxi: 13 },
  "缪": { char: "缪", simplified: 14, traditional: 17, traditionalChar: "繆", kangxi: 17 },
  "繆": { char: "繆", simplified: 17, traditional: 17, kangxi: 17 },
  "干": { char: "干", simplified: 3, traditional: 3, kangxi: 3 },
  "解": { char: "解", simplified: 13, traditional: 13, kangxi: 13 },
  "应": { char: "应", simplified: 7, traditional: 17, traditionalChar: "應", kangxi: 17 },
  "應": { char: "應", simplified: 17, traditional: 17, kangxi: 17 },
  "宗": { char: "宗", simplified: 8, traditional: 8, kangxi: 8 },
  "宣": { char: "宣", simplified: 9, traditional: 9, kangxi: 9 },
  "郁": { char: "郁", simplified: 8, traditional: 29, traditionalChar: "鬱", kangxi: 29 },
  "单": { char: "单", simplified: 8, traditional: 12, traditionalChar: "單", kangxi: 12 },
  "單": { char: "單", simplified: 12, traditional: 12, kangxi: 12 },
  "杭": { char: "杭", simplified: 8, traditional: 8, kangxi: 8 },
  "洪": { char: "洪", simplified: 9, traditional: 9, kangxi: 9 },
  "包": { char: "包", simplified: 5, traditional: 5, kangxi: 5 },
  "诸": { char: "诸", simplified: 10, traditional: 16, traditionalChar: "諸", kangxi: 16 },
  "諸": { char: "諸", simplified: 16, traditional: 16, kangxi: 16 },
  "左": { char: "左", simplified: 5, traditional: 5, kangxi: 5 },
  "吉": { char: "吉", simplified: 6, traditional: 6, kangxi: 6 },
  "嵇": { char: "嵇", simplified: 12, traditional: 12, kangxi: 12 },
  "邢": { char: "邢", simplified: 6, traditional: 6, kangxi: 6 },
  "滑": { char: "滑", simplified: 12, traditional: 12, kangxi: 12 },
  "裴": { char: "裴", simplified: 14, traditional: 14, kangxi: 14 },
  "荣": { char: "荣", simplified: 9, traditional: 14, kangxi: 14 },
  "榮": { char: "榮", simplified: 14, traditional: 14, kangxi: 14 },
  "翁": { char: "翁", simplified: 10, traditional: 10, kangxi: 10 },
  "荀": { char: "荀", simplified: 9, traditional: 9, kangxi: 9 },
  "羊": { char: "羊", simplified: 6, traditional: 6, kangxi: 6 },
  "於": { char: "於", simplified: 8, traditional: 8, kangxi: 8 },
  "惠": { char: "惠", simplified: 12, traditional: 12, kangxi: 12 },
  "甄": { char: "甄", simplified: 13, traditional: 13, kangxi: 13 },
  "曲": { char: "曲", simplified: 6, traditional: 6, kangxi: 6 },
  "封": { char: "封", simplified: 9, traditional: 9, kangxi: 9 },
  "芮": { char: "芮", simplified: 7, traditional: 7, kangxi: 7 },
  "羿": { char: "羿", simplified: 9, traditional: 9, kangxi: 9 },
  "储": { char: "储", simplified: 12, traditional: 17, traditionalChar: "儲", kangxi: 17 },
  "儲": { char: "儲", simplified: 17, traditional: 17, kangxi: 17 },
  "靳": { char: "靳", simplified: 13, traditional: 13, kangxi: 13 },
  "汲": { char: "汲", simplified: 6, traditional: 6, kangxi: 6 },
  "邴": { char: "邴", simplified: 7, traditional: 7, kangxi: 7 },
  "糜": { char: "糜", simplified: 17, traditional: 17, kangxi: 17 },
  "松": { char: "松", simplified: 8, traditional: 8, kangxi: 8 },
  "富": { char: "富", simplified: 12, traditional: 12, kangxi: 12 },
  "巫": { char: "巫", simplified: 7, traditional: 7, kangxi: 7 },
  "乌": { char: "乌", simplified: 4, traditional: 10, traditionalChar: "烏", kangxi: 10 },
  "烏": { char: "烏", simplified: 10, traditional: 10, kangxi: 10 },
  "焦": { char: "焦", simplified: 12, traditional: 12, kangxi: 12 },
  "巴": { char: "巴", simplified: 4, traditional: 4, kangxi: 4 },
  "弓": { char: "弓", simplified: 3, traditional: 3, kangxi: 3 },
  "牧": { char: "牧", simplified: 8, traditional: 8, kangxi: 8 },
  "隗": { char: "隗", simplified: 12, traditional: 12, kangxi: 12 },
  "山": { char: "山", simplified: 3, traditional: 3, kangxi: 3 },
  "谷": { char: "谷", simplified: 7, traditional: 7, kangxi: 7 },
  "车": { char: "车", simplified: 4, traditional: 7, traditionalChar: "車", kangxi: 7 },
  "車": { char: "車", simplified: 7, traditional: 7, kangxi: 7 },
  "宓": { char: "宓", simplified: 8, traditional: 8, kangxi: 8 },
  "蓬": { char: "蓬", simplified: 13, traditional: 13, kangxi: 13 },
  "全": { char: "全", simplified: 6, traditional: 6, kangxi: 6 },
  "郗": { char: "郗", simplified: 9, traditional: 9, kangxi: 9 },
  "班": { char: "班", simplified: 10, traditional: 10, kangxi: 10 },
  "仰": { char: "仰", simplified: 6, traditional: 6, kangxi: 6 },
  "仲": { char: "仲", simplified: 6, traditional: 6, kangxi: 6 },
  "伊": { char: "伊", simplified: 6, traditional: 6, kangxi: 6 },
  "宫": { char: "宫", simplified: 9, traditional: 10, traditionalChar: "宮", kangxi: 10 },
  "宮": { char: "宮", simplified: 10, traditional: 10, kangxi: 10 },
  "宁": { char: "宁", simplified: 5, traditional: 14, traditionalChar: "寧", kangxi: 14 },
  "寧": { char: "寧", simplified: 14, traditional: 14, kangxi: 14 },
  "仇": { char: "仇", simplified: 4, traditional: 4, kangxi: 4 },
  "栾": { char: "栾", simplified: 10, traditional: 23, traditionalChar: "欒", kangxi: 23 },
  "欒": { char: "欒", simplified: 23, traditional: 23, kangxi: 23 },
  "暴": { char: "暴", simplified: 15, traditional: 15, kangxi: 15 },
  "甘": { char: "甘", simplified: 5, traditional: 5, kangxi: 5 },
  "厉": { char: "厉", simplified: 5, traditional: 14, traditionalChar: "厲", kangxi: 14 },
  "厲": { char: "厲", simplified: 14, traditional: 14, kangxi: 14 },
  "戎": { char: "戎", simplified: 6, traditional: 6, kangxi: 6 },
  "祖": { char: "祖", simplified: 9, traditional: 9, kangxi: 9 },
  "符": { char: "符", simplified: 11, traditional: 11, kangxi: 11 },
  "景": { char: "景", simplified: 12, traditional: 12, kangxi: 12 },
  "詹": { char: "詹", simplified: 13, traditional: 13, kangxi: 13 },
  "幸": { char: "幸", simplified: 8, traditional: 8, kangxi: 8 },
  "司": { char: "司", simplified: 5, traditional: 5, kangxi: 5 },
  "韶": { char: "韶", simplified: 14, traditional: 14, kangxi: 14 },
  "蓟": { char: "蓟", simplified: 13, traditional: 16, traditionalChar: "薊", kangxi: 16 },
  "薊": { char: "薊", simplified: 16, traditional: 16, kangxi: 16 },
  "薄": { char: "薄", simplified: 16, traditional: 16, kangxi: 16 },
  "印": { char: "印", simplified: 6, traditional: 6, kangxi: 6 },
  "宿": { char: "宿", simplified: 11, traditional: 11, kangxi: 11 },
  "怀": { char: "怀", simplified: 7, traditional: 19, traditionalChar: "懷", kangxi: 19 },
  "懷": { char: "懷", simplified: 19, traditional: 19, kangxi: 19 },
  "蒲": { char: "蒲", simplified: 13, traditional: 13, kangxi: 13 },
  "邰": { char: "邰", simplified: 7, traditional: 7, kangxi: 7 },
  "从": { char: "从", simplified: 4, traditional: 11, traditionalChar: "從", kangxi: 11 },
  "從": { char: "從", simplified: 11, traditional: 11, kangxi: 11 },
  "鄂": { char: "鄂", simplified: 11, traditional: 11, kangxi: 11 },
  "索": { char: "索", simplified: 10, traditional: 10, kangxi: 10 },
  "咸": { char: "咸", simplified: 9, traditional: 9, kangxi: 9 },
  "籍": { char: "籍", simplified: 14, traditional: 14, kangxi: 14 },
  "蔺": { char: "蔺", simplified: 14, traditional: 22, traditionalChar: "藺", kangxi: 22 },
  "藺": { char: "藺", simplified: 22, traditional: 22, kangxi: 22 },
  "屠": { char: "屠", simplified: 11, traditional: 11, kangxi: 11 },
  "蒙": { char: "蒙", simplified: 13, traditional: 13, kangxi: 13 },
  "池": { char: "池", simplified: 6, traditional: 6, kangxi: 6 },
  "阳": { char: "阳", simplified: 6, traditional: 11, traditionalChar: "陽", kangxi: 11 },
  "陽": { char: "陽", simplified: 11, traditional: 11, kangxi: 11 },
  "胥": { char: "胥", simplified: 9, traditional: 9, kangxi: 9 },
  "能": { char: "能", simplified: 10, traditional: 10, kangxi: 10 },
  "苍": { char: "苍", simplified: 7, traditional: 16, traditionalChar: "蒼", kangxi: 16 },
  "蒼": { char: "蒼", simplified: 16, traditional: 16, kangxi: 16 },
  "双": { char: "双", simplified: 4, traditional: 18, traditionalChar: "雙", kangxi: 18 },
  "雙": { char: "雙", simplified: 18, traditional: 18, kangxi: 18 },
  "闻": { char: "闻", simplified: 9, traditional: 14, traditionalChar: "聞", kangxi: 14 },
  "聞": { char: "聞", simplified: 14, traditional: 14, kangxi: 14 },
  "莘": { char: "莘", simplified: 10, traditional: 10, kangxi: 10 },
  "党": { char: "党", simplified: 6, traditional: 20, traditionalChar: "黨", kangxi: 20 },
  "黨": { char: "黨", simplified: 20, traditional: 20, kangxi: 20 },
  "翟": { char: "翟", simplified: 14, traditional: 14, kangxi: 14 },
  "贡": { char: "贡", simplified: 7, traditional: 10, traditionalChar: "貢", kangxi: 10 },
  "貢": { char: "貢", simplified: 10, traditional: 10, kangxi: 10 },
  "劳": { char: "劳", simplified: 7, traditional: 12, traditionalChar: "勞", kangxi: 12 },
  "勞": { char: "勞", simplified: 12, traditional: 12, kangxi: 12 },
  "逄": { char: "逄", simplified: 10, traditional: 10, kangxi: 10 },
  "姬": { char: "姬", simplified: 10, traditional: 10, kangxi: 10 },
  "申": { char: "申", simplified: 5, traditional: 5, kangxi: 5 },
  "扶": { char: "扶", simplified: 7, traditional: 7, kangxi: 7 },
  "堵": { char: "堵", simplified: 11, traditional: 11, kangxi: 11 },
  "冉": { char: "冉", simplified: 5, traditional: 5, kangxi: 5 },
  "宰": { char: "宰", simplified: 10, traditional: 10, kangxi: 10 },
  "郦": { char: "郦", simplified: 9, traditional: 21, traditionalChar: "酈", kangxi: 21 },
  "酈": { char: "酈", simplified: 21, traditional: 21, kangxi: 21 },
  "雍": { char: "雍", simplified: 13, traditional: 13, kangxi: 13 },
  "璩": { char: "璩", simplified: 17, traditional: 17, kangxi: 17 },
  "桑": { char: "桑", simplified: 10, traditional: 10, kangxi: 10 },
  "桂": { char: "桂", simplified: 10, traditional: 10, kangxi: 10 },
  "濮": { char: "濮", simplified: 17, traditional: 17, kangxi: 17 },
  "牛": { char: "牛", simplified: 4, traditional: 4, kangxi: 4 },
  "通": { char: "通", simplified: 10, traditional: 10, kangxi: 10 },
  "边": { char: "边", simplified: 5, traditional: 18, traditionalChar: "邊", kangxi: 18 },
  "邊": { char: "邊", simplified: 18, traditional: 18, kangxi: 18 },
  "扈": { char: "扈", simplified: 11, traditional: 11, kangxi: 11 },
  "燕": { char: "燕", simplified: 16, traditional: 16, kangxi: 16 },
  "冀": { char: "冀", simplified: 16, traditional: 16, kangxi: 16 },
  "浦": { char: "浦", simplified: 10, traditional: 10, kangxi: 10 },
  "尚": { char: "尚", simplified: 8, traditional: 8, kangxi: 8 },
  "农": { char: "农", simplified: 6, traditional: 13, traditionalChar: "農", kangxi: 13 },
  "農": { char: "農", simplified: 13, traditional: 13, kangxi: 13 },
  "温": { char: "温", simplified: 12, traditional: 13, traditionalChar: "溫", kangxi: 13 },
  "溫": { char: "溫", simplified: 13, traditional: 13, kangxi: 13 },
  "别": { char: "别", simplified: 7, traditional: 7, kangxi: 7 },
  "庄": { char: "庄", simplified: 6, traditional: 13, traditionalChar: "莊", kangxi: 13 },
  "莊": { char: "莊", simplified: 13, traditional: 13, kangxi: 13 },
  "晏": { char: "晏", simplified: 10, traditional: 10, kangxi: 10 },
  "柴": { char: "柴", simplified: 10, traditional: 10, kangxi: 10 },
  "瞿": { char: "瞿", simplified: 18, traditional: 18, kangxi: 18 },
  "充": { char: "充", simplified: 6, traditional: 6, kangxi: 6 },
  "慕": { char: "慕", simplified: 14, traditional: 14, kangxi: 14 },
  "连": { char: "连", simplified: 7, traditional: 10, traditionalChar: "連", kangxi: 10 },
  "連": { char: "連", simplified: 10, traditional: 10, kangxi: 10 },
  "茹": { char: "茹", simplified: 9, traditional: 9, kangxi: 9 },
  "习": { char: "习", simplified: 3, traditional: 11, traditionalChar: "習", kangxi: 11 },
  "習": { char: "習", simplified: 11, traditional: 11, kangxi: 11 },
  "宦": { char: "宦", simplified: 9, traditional: 9, kangxi: 9 },
  "艾": { char: "艾", simplified: 5, traditional: 5, kangxi: 5 },
  "鱼": { char: "鱼", simplified: 8, traditional: 11, traditionalChar: "魚", kangxi: 11 },
  "魚": { char: "魚", simplified: 11, traditional: 11, kangxi: 11 },
  "容": { char: "容", simplified: 10, traditional: 10, kangxi: 10 },
  "向": { char: "向", simplified: 6, traditional: 6, kangxi: 6 },
  "古": { char: "古", simplified: 5, traditional: 5, kangxi: 5 },
  "慎": { char: "慎", simplified: 13, traditional: 13, kangxi: 13 },
  "戈": { char: "戈", simplified: 4, traditional: 4, kangxi: 4 },
  "庾": { char: "庾", simplified: 11, traditional: 11, kangxi: 11 },
  "终": { char: "终", simplified: 8, traditional: 11, traditionalChar: "終", kangxi: 11 },
  "終": { char: "終", simplified: 11, traditional: 11, kangxi: 11 },
  "暨": { char: "暨", simplified: 14, traditional: 14, kangxi: 14 },
  "居": { char: "居", simplified: 8, traditional: 8, kangxi: 8 },
  "衡": { char: "衡", simplified: 16, traditional: 16, kangxi: 16 },
  "步": { char: "步", simplified: 7, traditional: 7, kangxi: 7 },
  "都": { char: "都", simplified: 10, traditional: 10, kangxi: 10 },
  "耿": { char: "耿", simplified: 10, traditional: 10, kangxi: 10 },
  "满": { char: "满", simplified: 13, traditional: 14, traditionalChar: "滿", kangxi: 14 },
  "滿": { char: "滿", simplified: 14, traditional: 14, kangxi: 14 },
  "弘": { char: "弘", simplified: 5, traditional: 5, kangxi: 5 },
  "匡": { char: "匡", simplified: 6, traditional: 6, kangxi: 6 },
  "寇": { char: "寇", simplified: 11, traditional: 11, kangxi: 11 },
  "广": { char: "广", simplified: 3, traditional: 14, kangxi: 14 },
  "廣": { char: "廣", simplified: 14, traditional: 14, kangxi: 14 },
  "禄": { char: "禄", simplified: 11, traditional: 21, traditionalChar: "祿", kangxi: 21 },
  "祿": { char: "祿", simplified: 21, traditional: 21, kangxi: 21 },
  "阙": { char: "阙", simplified: 13, traditional: 18, traditionalChar: "闕", kangxi: 18 },
  "闕": { char: "闕", simplified: 18, traditional: 18, kangxi: 18 },
  "东": { char: "东", simplified: 5, traditional: 8, kangxi: 8 },
  "東": { char: "東", simplified: 8, traditional: 8, kangxi: 8 },
  "欧": { char: "欧", simplified: 8, traditional: 15, traditionalChar: "歐", kangxi: 15 },
  "歐": { char: "歐", simplified: 15, traditional: 15, kangxi: 15 },
  "殳": { char: "殳", simplified: 4, traditional: 4, kangxi: 4 },
  "沃": { char: "沃", simplified: 7, traditional: 7, kangxi: 7 },
  "利": { char: "利", simplified: 7, traditional: 7, kangxi: 7 },
  "蔚": { char: "蔚", simplified: 14, traditional: 14, kangxi: 14 },
  "越": { char: "越", simplified: 12, traditional: 12, kangxi: 12 },
  "夔": { char: "夔", simplified: 21, traditional: 21, kangxi: 21 },
  "隆": { char: "隆", simplified: 11, traditional: 11, kangxi: 11 },
  "师": { char: "师", simplified: 6, traditional: 10, traditionalChar: "師", kangxi: 10 },
  "師": { char: "師", simplified: 10, traditional: 10, kangxi: 10 },
  "巩": { char: "巩", simplified: 6, traditional: 9, traditionalChar: "鞏", kangxi: 9 },
  "鞏": { char: "鞏", simplified: 9, traditional: 9, kangxi: 9 },
  "厍": { char: "厍", simplified: 6, traditional: 6, kangxi: 6 },
  "聂": { char: "聂", simplified: 10, traditional: 18, traditionalChar: "聶", kangxi: 18 },
  "聶": { char: "聶", simplified: 18, traditional: 18, kangxi: 18 },
  "晁": { char: "晁", simplified: 10, traditional: 10, kangxi: 10 },
  "勾": { char: "勾", simplified: 4, traditional: 4, kangxi: 4 },
  "敖": { char: "敖", simplified: 10, traditional: 10, kangxi: 10 },
  "融": { char: "融", simplified: 16, traditional: 16, kangxi: 16 },
  "冷": { char: "冷", simplified: 7, traditional: 7, kangxi: 7 },
  "訾": { char: "訾", simplified: 13, traditional: 13, kangxi: 13 },
  "辛": { char: "辛", simplified: 7, traditional: 7, kangxi: 7 },
  "阚": { char: "阚", simplified: 14, traditional: 20, traditionalChar: "闞", kangxi: 20 },
  "闞": { char: "闞", simplified: 20, traditional: 20, kangxi: 20 },
  "那": { char: "那", simplified: 6, traditional: 6, kangxi: 6 },
  "简": { char: "简", simplified: 13, traditional: 18, traditionalChar: "簡", kangxi: 18 },
  "簡": { char: "簡", simplified: 18, traditional: 18, kangxi: 18 },
  "饶": { char: "饶", simplified: 9, traditional: 21, traditionalChar: "饒", kangxi: 21 },
  "饒": { char: "饒", simplified: 21, traditional: 21, kangxi: 21 },
  "空": { char: "空", simplified: 8, traditional: 8, kangxi: 8 },
  "毋": { char: "毋", simplified: 4, traditional: 4, kangxi: 4 },
  "沙": { char: "沙", simplified: 7, traditional: 7, kangxi: 7 },
  "乜": { char: "乜", simplified: 2, traditional: 2, kangxi: 2 },
  "养": { char: "养", simplified: 9, traditional: 14, traditionalChar: "養", kangxi: 14 },
  "養": { char: "養", simplified: 14, traditional: 14, kangxi: 14 },
  "鞠": { char: "鞠", simplified: 17, traditional: 17, kangxi: 17 },
  "须": { char: "须", simplified: 9, traditional: 12, traditionalChar: "須", kangxi: 12 },
  "須": { char: "須", simplified: 12, traditional: 12, kangxi: 12 },
  "丰": { char: "丰", simplified: 4, traditional: 18, traditionalChar: "豐", kangxi: 18 },
  "豐": { char: "豐", simplified: 18, traditional: 18, kangxi: 18 },
  "巢": { char: "巢", simplified: 11, traditional: 11, kangxi: 11 },
  "关": { char: "关", simplified: 6, traditional: 19, traditionalChar: "關", kangxi: 19 },
  "關": { char: "關", simplified: 19, traditional: 19, kangxi: 19 },
  "蒯": { char: "蒯", simplified: 13, traditional: 13, kangxi: 13 },
  "相": { char: "相", simplified: 9, traditional: 9, kangxi: 9 },
  "查": { char: "查", simplified: 9, traditional: 9, kangxi: 9 },
  "后": { char: "后", simplified: 6, traditional: 9, traditionalChar: "後", kangxi: 9 },
  "後": { char: "後", simplified: 9, traditional: 9, kangxi: 9 },
  "荆": { char: "荆", simplified: 9, traditional: 12, traditionalChar: "荊", kangxi: 12 },
  "荊": { char: "荊", simplified: 12, traditional: 12, kangxi: 12 },
  "游": { char: "游", simplified: 12, traditional: 12, kangxi: 12 },
  "竺": { char: "竺", simplified: 8, traditional: 8, kangxi: 8 },
  "权": { char: "权", simplified: 6, traditional: 22, traditionalChar: "權", kangxi: 22 },
  "權": { char: "權", simplified: 22, traditional: 22, kangxi: 22 },
  "逯": { char: "逯", simplified: 11, traditional: 11, kangxi: 11 },
  "盖": { char: "盖", simplified: 11, traditional: 13, traditionalChar: "蓋", kangxi: 13 },
  "蓋": { char: "蓋", simplified: 13, traditional: 13, kangxi: 13 },
  "益": { char: "益", simplified: 10, traditional: 10, kangxi: 10 },
  "公": { char: "公", simplified: 4, traditional: 4, kangxi: 4 },
  "刚": { char: "刚", simplified: 6, traditional: 10, traditionalChar: "剛", kangxi: 10 },
  "剛": { char: "剛", simplified: 10, traditional: 10, kangxi: 10 },
  "毅": { char: "毅", simplified: 15, traditional: 15, kangxi: 15 },
  "俊": { char: "俊", simplified: 9, traditional: 9, kangxi: 9 },
  "峰": { char: "峰", simplified: 10, traditional: 10, kangxi: 10 },
  "保": { char: "保", simplified: 9, traditional: 9, kangxi: 9 },
  "辉": { char: "辉", simplified: 12, traditional: 15, traditionalChar: "輝", kangxi: 15 },
  "輝": { char: "輝", simplified: 15, traditional: 15, kangxi: 15 },
  "力": { char: "力", simplified: 2, traditional: 2, kangxi: 2 },
  "健": { char: "健", simplified: 11, traditional: 11, kangxi: 11 },
  "良": { char: "良", simplified: 7, traditional: 7, kangxi: 7 },
  "海": { char: "海", simplified: 10, traditional: 10, kangxi: 10 },
  "波": { char: "波", simplified: 8, traditional: 8, kangxi: 8 },
  "贵": { char: "贵", simplified: 9, traditional: 12, traditionalChar: "貴", kangxi: 12 },
  "貴": { char: "貴", simplified: 12, traditional: 12, kangxi: 12 },
  "生": { char: "生", simplified: 5, traditional: 5, kangxi: 5 },
  "胜": { char: "胜", simplified: 9, traditional: 12, traditionalChar: "勝", kangxi: 12 },
  "勝": { char: "勝", simplified: 12, traditional: 12, kangxi: 12 },
  "学": { char: "学", simplified: 8, traditional: 16, traditionalChar: "學", kangxi: 16 },
  "學": { char: "學", simplified: 16, traditional: 16, kangxi: 16 },
  "祥": { char: "祥", simplified: 10, traditional: 10, kangxi: 10 },
  "才": { char: "才", simplified: 3, traditional: 3, kangxi: 3 },
  "发": { char: "发", simplified: 5, traditional: 12, traditionalChar: "發", kangxi: 12 },
  "發": { char: "發", simplified: 12, traditional: 12, kangxi: 12 },
  "清": { char: "清", simplified: 11, traditional: 11, kangxi: 11 },
  "飞": { char: "飞", simplified: 3, traditional: 9, traditionalChar: "飛", kangxi: 9 },
  "飛": { char: "飛", simplified: 9, traditional: 9, kangxi: 9 },
  "彬": { char: "彬", simplified: 11, traditional: 11, kangxi: 11 },
  "顺": { char: "顺", simplified: 9, traditional: 18, traditionalChar: "順", kangxi: 18 },
  "順": { char: "順", simplified: 18, traditional: 18, kangxi: 18 },
  "星": { char: "星", simplified: 9, traditional: 9, kangxi: 9 },
  "光": { char: "光", simplified: 6, traditional: 6, kangxi: 6 },
  "达": { char: "达", simplified: 6, traditional: 12, traditionalChar: "達", kangxi: 12 },
  "達": { char: "達", simplified: 12, traditional: 12, kangxi: 12 },
  "岩": { char: "岩", simplified: 8, traditional: 8, kangxi: 8 },
  "茂": { char: "茂", simplified: 8, traditional: 8, kangxi: 8 },
  "进": { char: "进", simplified: 7, traditional: 12, traditionalChar: "進", kangxi: 12 },
  "進": { char: "進", simplified: 12, traditional: 12, kangxi: 12 },
  "有": { char: "有", simplified: 6, traditional: 6, kangxi: 6 },
  "坚": { char: "坚", simplified: 7, traditional: 11, traditionalChar: "堅", kangxi: 11 },
  "堅": { char: "堅", simplified: 11, traditional: 11, kangxi: 11 },
  "彪": { char: "彪", simplified: 11, traditional: 11, kangxi: 11 },
  "博": { char: "博", simplified: 12, traditional: 12, kangxi: 12 },
  "诚": { char: "诚", simplified: 8, traditional: 14, traditionalChar: "誠", kangxi: 14 },
  "誠": { char: "誠", simplified: 14, traditional: 14, kangxi: 14 },
  "先": { char: "先", simplified: 6, traditional: 6, kangxi: 6 },
  "敬": { char: "敬", simplified: 12, traditional: 12, kangxi: 12 },
  "震": { char: "震", simplified: 15, traditional: 15, kangxi: 15 },
  "振": { char: "振", simplified: 10, traditional: 10, kangxi: 10 },
  "壮": { char: "壮", simplified: 6, traditional: 11, traditionalChar: "壯", kangxi: 11 },
  "壯": { char: "壯", simplified: 11, traditional: 11, kangxi: 11 },
  "会": { char: "会", simplified: 6, traditional: 13, traditionalChar: "會", kangxi: 13 },
  "會": { char: "會", simplified: 13, traditional: 13, kangxi: 13 },
  "思": { char: "思", simplified: 9, traditional: 9, kangxi: 9 },
  "群": { char: "群", simplified: 13, traditional: 13, kangxi: 13 },
  "豪": { char: "豪", simplified: 14, traditional: 14, kangxi: 14 },
  "邦": { char: "邦", simplified: 6, traditional: 6, kangxi: 6 },
  "承": { char: "承", simplified: 8, traditional: 8, kangxi: 8 },
  "绍": { char: "绍", simplified: 8, traditional: 11, traditionalChar: "紹", kangxi: 11 },
  "紹": { char: "紹", simplified: 11, traditional: 11, kangxi: 11 },
  "功": { char: "功", simplified: 5, traditional: 5, kangxi: 5 },
  "善": { char: "善", simplified: 12, traditional: 12, kangxi: 12 },
  "厚": { char: "厚", simplified: 9, traditional: 9, kangxi: 9 },
  "庆": { char: "庆", simplified: 6, traditional: 15, traditionalChar: "慶", kangxi: 15 },
  "慶": { char: "慶", simplified: 15, traditional: 15, kangxi: 15 },
  "民": { char: "民", simplified: 5, traditional: 5, kangxi: 5 },
  "友": { char: "友", simplified: 4, traditional: 4, kangxi: 4 },
  "裕": { char: "裕", simplified: 12, traditional: 12, kangxi: 12 },
  "河": { char: "河", simplified: 8, traditional: 8, kangxi: 8 },
  "哲": { char: "哲", simplified: 10, traditional: 10, kangxi: 10 },
  "浩": { char: "浩", simplified: 10, traditional: 10, kangxi: 10 },
  "亮": { char: "亮", simplified: 9, traditional: 9, kangxi: 9 },
  "政": { char: "政", simplified: 9, traditional: 9, kangxi: 9 },
  "谦": { char: "谦", simplified: 12, traditional: 17, traditionalChar: "謙", kangxi: 17 },
  "謙": { char: "謙", simplified: 17, traditional: 17, kangxi: 17 },
  "亨": { char: "亨", simplified: 7, traditional: 7, kangxi: 7 },
  "奇": { char: "奇", simplified: 8, traditional: 8, kangxi: 8 },
  "固": { char: "固", simplified: 8, traditional: 8, kangxi: 8 },
  "之": { char: "之", simplified: 3, traditional: 3, kangxi: 3 },
  "轮": { char: "轮", simplified: 8, traditional: 15, traditionalChar: "輪", kangxi: 15 },
  "輪": { char: "輪", simplified: 15, traditional: 15, kangxi: 15 },
  "翰": { char: "翰", simplified: 16, traditional: 16, kangxi: 16 },
  "朗": { char: "朗", simplified: 10, traditional: 10, kangxi: 10 },
  "伯": { char: "伯", simplified: 7, traditional: 7, kangxi: 7 },
  "宏": { char: "宏", simplified: 7, traditional: 7, kangxi: 7 },
  "言": { char: "言", simplified: 7, traditional: 7, kangxi: 7 },
  "若": { char: "若", simplified: 8, traditional: 8, kangxi: 8 },
  "鸣": { char: "鸣", simplified: 8, traditional: 14, traditionalChar: "鳴", kangxi: 14 },
  "鳴": { char: "鳴", simplified: 14, traditional: 14, kangxi: 14 },
  "朋": { char: "朋", simplified: 8, traditional: 8, kangxi: 8 },
  "斌": { char: "斌", simplified: 12, traditional: 12, kangxi: 12 },
  "栋": { char: "栋", simplified: 9, traditional: 12, traditionalChar: "棟", kangxi: 12 },
  "棟": { char: "棟", simplified: 12, traditional: 12, kangxi: 12 },
  "维": { char: "维", simplified: 11, traditional: 14, traditionalChar: "維", kangxi: 14 },
  "維": { char: "維", simplified: 14, traditional: 14, kangxi: 14 },
  "启": { char: "启", simplified: 7, traditional: 11, traditionalChar: "啟", kangxi: 11 },
  "啟": { char: "啟", simplified: 11, traditional: 11, kangxi: 11 },
  "克": { char: "克", simplified: 7, traditional: 7, kangxi: 7 },
  "伦": { char: "伦", simplified: 6, traditional: 10, traditionalChar: "倫", kangxi: 10 },
  "倫": { char: "倫", simplified: 10, traditional: 10, kangxi: 10 },
  "翔": { char: "翔", simplified: 12, traditional: 12, kangxi: 12 },
  "旭": { char: "旭", simplified: 6, traditional: 6, kangxi: 6 },
  "鹏": { char: "鹏", simplified: 13, traditional: 19, traditionalChar: "鵬", kangxi: 19 },
  "鵬": { char: "鵬", simplified: 19, traditional: 19, kangxi: 19 },
  "泽": { char: "泽", simplified: 8, traditional: 16, traditionalChar: "澤", kangxi: 16 },
  "澤": { char: "澤", simplified: 16, traditional: 16, kangxi: 16 },
  "晨": { char: "晨", simplified: 11, traditional: 11, kangxi: 11 },
  "辰": { char: "辰", simplified: 7, traditional: 7, kangxi: 7 },
  "宇": { char: "宇", simplified: 6, traditional: 6, kangxi: 6 },
  "轩": { char: "轩", simplified: 7, traditional: 10, traditionalChar: "軒", kangxi: 10 },
  "軒": { char: "軒", simplified: 10, traditional: 10, kangxi: 10 },
  "昊": { char: "昊", simplified: 8, traditional: 8, kangxi: 8 },
  "睿": { char: "睿", simplified: 14, traditional: 14, kangxi: 14 },
  "然": { char: "然", simplified: 12, traditional: 12, kangxi: 12 },
  "航": { char: "航", simplified: 10, traditional: 10, kangxi: 10 },
  "鑫": { char: "鑫", simplified: 24, traditional: 24, kangxi: 24 },
  "铭": { char: "铭", simplified: 11, traditional: 14, traditionalChar: "銘", kangxi: 14 },
  "銘": { char: "銘", simplified: 14, traditional: 14, kangxi: 14 },
  "皓": { char: "皓", simplified: 12, traditional: 12, kangxi: 12 },
  "凯": { char: "凯", simplified: 8, traditional: 12, traditionalChar: "凱", kangxi: 12 },
  "凱": { char: "凱", simplified: 12, traditional: 12, kangxi: 12 },
  "瑞": { char: "瑞", simplified: 13, traditional: 13, kangxi: 13 },
  "霖": { char: "霖", simplified: 16, traditional: 16, kangxi: 16 },
  "嘉": { char: "嘉", simplified: 14, traditional: 14, kangxi: 14 },
  "楠": { char: "楠", simplified: 13, traditional: 13, kangxi: 13 },
  "帆": { char: "帆", simplified: 6, traditional: 6, kangxi: 6 },
  "煜": { char: "煜", simplified: 13, traditional: 13, kangxi: 13 },
  "炜": { char: "炜", simplified: 8, traditional: 13, traditionalChar: "煒", kangxi: 13 },
  "煒": { char: "煒", simplified: 13, traditional: 13, kangxi: 13 },
  "奕": { char: "奕", simplified: 9, traditional: 9, kangxi: 9 },
  "彦": { char: "彦", simplified: 9, traditional: 9, kangxi: 9 },
  "骏": { char: "骏", simplified: 10, traditional: 17, traditionalChar: "駿", kangxi: 17 },
  "駿": { char: "駿", simplified: 17, traditional: 17, kangxi: 17 },
  "晟": { char: "晟", simplified: 10, traditional: 10, kangxi: 10 },
  "鸿": { char: "鸿", simplified: 11, traditional: 17, traditionalChar: "鴻", kangxi: 17 },
  "鴻": { char: "鴻", simplified: 17, traditional: 17, kangxi: 17 },
  "宸": { char: "宸", simplified: 10, traditional: 10, kangxi: 10 },
  "坤": { char: "坤", simplified: 8, traditional: 8, kangxi: 8 },
  "尧": { char: "尧", simplified: 6, traditional: 12, traditionalChar: "堯", kangxi: 12 },
  "堯": { char: "堯", simplified: 12, traditional: 12, kangxi: 12 },
  "尘": { char: "尘", simplified: 6, traditional: 14, traditionalChar: "塵", kangxi: 14 },
  "塵": { char: "塵", simplified: 14, traditional: 14, kangxi: 14 },
  "祺": { char: "祺", simplified: 12, traditional: 12, kangxi: 12 },
  "佑": { char: "佑", simplified: 7, traditional: 7, kangxi: 7 },
  "恒": { char: "恒", simplified: 9, traditional: 9, kangxi: 9 },
  "熙": { char: "熙", simplified: 14, traditional: 14, kangxi: 14 },
  "源": { char: "源", simplified: 13, traditional: 13, kangxi: 13 },
  "远": { char: "远", simplified: 7, traditional: 13, traditionalChar: "遠", kangxi: 13 },
  "遠": { char: "遠", simplified: 13, traditional: 13, kangxi: 13 },
  "森": { char: "森", simplified: 12, traditional: 12, kangxi: 12 },
  "诺": { char: "诺", simplified: 10, traditional: 15, traditionalChar: "諾", kangxi: 15 },
  "諾": { char: "諾", simplified: 15, traditional: 15, kangxi: 15 },
  "延": { char: "延", simplified: 6, traditional: 6, kangxi: 6 },
  "庭": { char: "庭", simplified: 9, traditional: 9, kangxi: 9 },
  "书": { char: "书", simplified: 4, traditional: 10, traditionalChar: "書", kangxi: 10 },
  "書": { char: "書", simplified: 10, traditional: 10, kangxi: 10 },
  "墨": { char: "墨", simplified: 15, traditional: 15, kangxi: 15 },
  "修": { char: "修", simplified: 9, traditional: 9, kangxi: 9 },
  "谨": { char: "谨", simplified: 13, traditional: 18, traditionalChar: "謹", kangxi: 18 },
  "謹": { char: "謹", simplified: 18, traditional: 18, kangxi: 18 },
  "瑜": { char: "瑜", simplified: 13, traditional: 13, kangxi: 13 },
  "珩": { char: "珩", simplified: 10, traditional: 10, kangxi: 10 },
  "璟": { char: "璟", simplified: 16, traditional: 16, kangxi: 16 },
  "钧": { char: "钧", simplified: 9, traditional: 12, traditionalChar: "鈞", kangxi: 12 },
  "鈞": { char: "鈞", simplified: 12, traditional: 12, kangxi: 12 },
  "锐": { char: "锐", simplified: 12, traditional: 15, traditionalChar: "銳", kangxi: 15 },
  "銳": { char: "銳", simplified: 15, traditional: 15, kangxi: 15 },
  "铠": { char: "铠", simplified: 10, traditional: 18, traditionalChar: "鎧", kangxi: 18 },
  "鎧": { char: "鎧", simplified: 18, traditional: 18, kangxi: 18 },
  "锦": { char: "锦", simplified: 13, traditional: 16, traditionalChar: "錦", kangxi: 16 },
  "錦": { char: "錦", simplified: 16, traditional: 16, kangxi: 16 },
  "铎": { char: "铎", simplified: 10, traditional: 20, traditionalChar: "鐸", kangxi: 20 },
  "鐸": { char: "鐸", simplified: 20, traditional: 20, kangxi: 20 },
  "铮": { char: "铮", simplified: 11, traditional: 16, traditionalChar: "錚", kangxi: 16 },
  "錚": { char: "錚", simplified: 16, traditional: 16, kangxi: 16 },
  "钰": { char: "钰", simplified: 10, traditional: 13, traditionalChar: "鈺", kangxi: 13 },
  "鈺": { char: "鈺", simplified: 13, traditional: 13, kangxi: 13 },
  "钊": { char: "钊", simplified: 7, traditional: 10, traditionalChar: "釗", kangxi: 10 },
  "釗": { char: "釗", simplified: 10, traditional: 10, kangxi: 10 },
  "钦": { char: "钦", simplified: 9, traditional: 12, traditionalChar: "欽", kangxi: 12 },
  "欽": { char: "欽", simplified: 12, traditional: 12, kangxi: 12 },
  "锋": { char: "锋", simplified: 12, traditional: 15, traditionalChar: "鋒", kangxi: 15 },
  "鋒": { char: "鋒", simplified: 15, traditional: 15, kangxi: 15 },
  "锡": { char: "锡", simplified: 13, traditional: 16, traditionalChar: "錫", kangxi: 16 },
  "錫": { char: "錫", simplified: 16, traditional: 16, kangxi: 16 },
  "铖": { char: "铖", simplified: 11, traditional: 14, traditionalChar: "鋮", kangxi: 14 },
  "鋮": { char: "鋮", simplified: 14, traditional: 14, kangxi: 14 },
  "莹": { char: "莹", simplified: 10, traditional: 15, traditionalChar: "瑩", kangxi: 15 },
  "瑩": { char: "瑩", simplified: 15, traditional: 15, kangxi: 15 },
  "晶": { char: "晶", simplified: 12, traditional: 12, kangxi: 12 },
  "娥": { char: "娥", simplified: 10, traditional: 10, kangxi: 10 },
  "洁": { char: "洁", simplified: 9, traditional: 16, traditionalChar: "潔", kangxi: 16 },
  "潔": { char: "潔", simplified: 16, traditional: 16, kangxi: 16 },
  "琳": { char: "琳", simplified: 12, traditional: 12, kangxi: 12 },
  "素": { char: "素", simplified: 10, traditional: 10, kangxi: 10 },
  "莲": { char: "莲", simplified: 10, traditional: 17, traditionalChar: "蓮", kangxi: 17 },
  "蓮": { char: "蓮", simplified: 17, traditional: 17, kangxi: 17 },
  "真": { char: "真", simplified: 10, traditional: 10, kangxi: 10 },
  "环": { char: "环", simplified: 8, traditional: 17, traditionalChar: "環", kangxi: 17 },
  "環": { char: "環", simplified: 17, traditional: 17, kangxi: 17 },
  "爱": { char: "爱", simplified: 10, traditional: 13, traditionalChar: "愛", kangxi: 13 },
  "愛": { char: "愛", simplified: 13, traditional: 13, kangxi: 13 },
  "妹": { char: "妹", simplified: 8, traditional: 8, kangxi: 8 },
  "香": { char: "香", simplified: 9, traditional: 9, kangxi: 9 },
  "月": { char: "月", simplified: 4, traditional: 4, kangxi: 4 },
  "媛": { char: "媛", simplified: 12, traditional: 12, kangxi: 12 },
  "凡": { char: "凡", simplified: 3, traditional: 3, kangxi: 3 },
  "佳": { char: "佳", simplified: 8, traditional: 8, kangxi: 8 },
  "琼": { char: "琼", simplified: 12, traditional: 18, traditionalChar: "瓊", kangxi: 18 },
  "瓊": { char: "瓊", simplified: 18, traditional: 18, kangxi: 18 },
  "勤": { char: "勤", simplified: 13, traditional: 13, kangxi: 13 },
  "珍": { char: "珍", simplified: 9, traditional: 9, kangxi: 9 },
  "贞": { char: "贞", simplified: 6, traditional: 10, traditionalChar: "貞", kangxi: 10 },
  "貞": { char: "貞", simplified: 10, traditional: 10, kangxi: 10 },
  "莉": { char: "莉", simplified: 10, traditional: 10, kangxi: 10 },
  "娣": { char: "娣", simplified: 10, traditional: 10, kangxi: 10 },
  "璧": { char: "璧", simplified: 18, traditional: 18, kangxi: 18 },
  "璐": { char: "璐", simplified: 17, traditional: 17, kangxi: 17 },
  "娅": { char: "娅", simplified: 9, traditional: 13, traditionalChar: "婭", kangxi: 13 },
  "婭": { char: "婭", simplified: 13, traditional: 13, kangxi: 13 },
  "琦": { char: "琦", simplified: 12, traditional: 12, kangxi: 12 },
  "妍": { char: "妍", simplified: 7, traditional: 7, kangxi: 7 },
  "茜": { char: "茜", simplified: 9, traditional: 9, kangxi: 9 },
  "珊": { char: "珊", simplified: 9, traditional: 9, kangxi: 9 },
  "莎": { char: "莎", simplified: 10, traditional: 10, kangxi: 10 },
  "黛": { char: "黛", simplified: 17, traditional: 17, kangxi: 17 },
  "青": { char: "青", simplified: 8, traditional: 8, kangxi: 8 },
  "倩": { char: "倩", simplified: 10, traditional: 10, kangxi: 10 },
  "姣": { char: "姣", simplified: 9, traditional: 9, kangxi: 9 },
  "婉": { char: "婉", simplified: 11, traditional: 11, kangxi: 11 },
  "娴": { char: "娴", simplified: 10, traditional: 16, traditionalChar: "嫻", kangxi: 16 },
  "嫻": { char: "嫻", simplified: 16, traditional: 16, kangxi: 16 },
  "瑾": { char: "瑾", simplified: 15, traditional: 15, kangxi: 15 },
  "颖": { char: "颖", simplified: 13, traditional: 16, traditionalChar: "穎", kangxi: 16 },
  "穎": { char: "穎", simplified: 16, traditional: 16, kangxi: 16 },
  "露": { char: "露", simplified: 21, traditional: 21, kangxi: 21 },
  "瑶": { char: "瑶", simplified: 14, traditional: 15, traditionalChar: "瑤", kangxi: 15 },
  "瑤": { char: "瑤", simplified: 15, traditional: 15, kangxi: 15 },
  "怡": { char: "怡", simplified: 8, traditional: 8, kangxi: 8 },
  "婵": { char: "婵", simplified: 11, traditional: 15, traditionalChar: "嬋", kangxi: 15 },
  "嬋": { char: "嬋", simplified: 15, traditional: 15, kangxi: 15 },
  "雁": { char: "雁", simplified: 12, traditional: 12, kangxi: 12 },
  "蓓": { char: "蓓", simplified: 13, traditional: 13, kangxi: 13 },
  "纨": { char: "纨", simplified: 6, traditional: 13, traditionalChar: "紈", kangxi: 13 },
  "紈": { char: "紈", simplified: 13, traditional: 13, kangxi: 13 },
  "仪": { char: "仪", simplified: 5, traditional: 15, traditionalChar: "儀", kangxi: 15 },
  "儀": { char: "儀", simplified: 15, traditional: 15, kangxi: 15 },
  "荷": { char: "荷", simplified: 10, traditional: 10, kangxi: 10 },
  "丹": { char: "丹", simplified: 4, traditional: 4, kangxi: 4 },
  "蓉": { char: "蓉", simplified: 13, traditional: 13, kangxi: 13 },
  "眉": { char: "眉", simplified: 9, traditional: 9, kangxi: 9 },
  "琴": { char: "琴", simplified: 12, traditional: 12, kangxi: 12 },
  "蕊": { char: "蕊", simplified: 15, traditional: 15, kangxi: 15 },
  "薇": { char: "薇", simplified: 16, traditional: 16, kangxi: 16 },
  "菁": { char: "菁", simplified: 11, traditional: 11, kangxi: 11 },
  "梦": { char: "梦", simplified: 11, traditional: 13, traditionalChar: "夢", kangxi: 13 },
  "夢": { char: "夢", simplified: 13, traditional: 13, kangxi: 13 },
  "岚": { char: "岚", simplified: 7, traditional: 12, traditionalChar: "嵐", kangxi: 12 },
  "嵐": { char: "嵐", simplified: 12, traditional: 12, kangxi: 12 },
  "苑": { char: "苑", simplified: 8, traditional: 8, kangxi: 8 },
  "婕": { char: "婕", simplified: 11, traditional: 11, kangxi: 11 },
  "馨": { char: "馨", simplified: 20, traditional: 20, kangxi: 20 },
  "瑗": { char: "瑗", simplified: 13, traditional: 14, kangxi: 14 },
  "琰": { char: "琰", simplified: 12, traditional: 12, kangxi: 12 },
  "韵": { char: "韵", simplified: 13, traditional: 19, traditionalChar: "韻", kangxi: 19 },
  "韻": { char: "韻", simplified: 19, traditional: 19, kangxi: 19 },
  "园": { char: "园", simplified: 7, traditional: 13, traditionalChar: "園", kangxi: 13 },
  "園": { char: "園", simplified: 13, traditional: 13, kangxi: 13 },
  "艺": { char: "艺", simplified: 4, traditional: 18, traditionalChar: "藝", kangxi: 18 },
  "藝": { char: "藝", simplified: 18, traditional: 18, kangxi: 18 },
  "咏": { char: "咏", simplified: 8, traditional: 12, traditionalChar: "詠", kangxi: 12 },
  "詠": { char: "詠", simplified: 12, traditional: 12, kangxi: 12 },
  "卿": { char: "卿", simplified: 10, traditional: 10, kangxi: 10 },
  "聪": { char: "聪", simplified: 15, traditional: 17, traditionalChar: "聰", kangxi: 17 },
  "聰": { char: "聰", simplified: 17, traditional: 17, kangxi: 17 },
  "澜": { char: "澜", simplified: 15, traditional: 20, traditionalChar: "瀾", kangxi: 20 },
  "瀾": { char: "瀾", simplified: 20, traditional: 20, kangxi: 20 },
  "纯": { char: "纯", simplified: 7, traditional: 17, traditionalChar: "純", kangxi: 17 },
  "純": { char: "純", simplified: 17, traditional: 17, kangxi: 17 },
  "毓": { char: "毓", simplified: 14, traditional: 14, kangxi: 14 },
  "悦": { char: "悦", simplified: 10, traditional: 10, kangxi: 10 },
  "昭": { char: "昭", simplified: 9, traditional: 9, kangxi: 9 },
  "冰": { char: "冰", simplified: 6, traditional: 6, kangxi: 6 },
  "爽": { char: "爽", simplified: 11, traditional: 11, kangxi: 11 },
  "琬": { char: "琬", simplified: 12, traditional: 12, kangxi: 12 },
  "茗": { char: "茗", simplified: 9, traditional: 9, kangxi: 9 },
  "羽": { char: "羽", simplified: 6, traditional: 6, kangxi: 6 },
  "希": { char: "希", simplified: 7, traditional: 7, kangxi: 7 },
  "欣": { char: "欣", simplified: 8, traditional: 8, kangxi: 8 },
  "飘": { char: "飘", simplified: 15, traditional: 20, traditionalChar: "飄", kangxi: 20 },
  "飄": { char: "飄", simplified: 20, traditional: 20, kangxi: 20 },
  "育": { char: "育", simplified: 8, traditional: 8, kangxi: 8 },
  "滢": { char: "滢", simplified: 13, traditional: 19, traditionalChar: "瀅", kangxi: 19 },
  "瀅": { char: "瀅", simplified: 19, traditional: 19, kangxi: 19 },
  "馥": { char: "馥", simplified: 18, traditional: 18, kangxi: 18 },
  "筠": { char: "筠", simplified: 13, traditional: 13, kangxi: 13 },
  "柔": { char: "柔", simplified: 9, traditional: 9, kangxi: 9 },
  "竹": { char: "竹", simplified: 6, traditional: 6, kangxi: 6 },
  "霭": { char: "霭", simplified: 19, traditional: 24, traditionalChar: "靄", kangxi: 24 },
  "靄": { char: "靄", simplified: 24, traditional: 24, kangxi: 24 },
  "凝": { char: "凝", simplified: 16, traditional: 16, kangxi: 16 },
  "欢": { char: "欢", simplified: 6, traditional: 21, traditionalChar: "歡", kangxi: 21 },
  "歡": { char: "歡", simplified: 21, traditional: 21, kangxi: 21 },
  "霄": { char: "霄", simplified: 15, traditional: 15, kangxi: 15 },
  "枫": { char: "枫", simplified: 8, traditional: 13, traditionalChar: "楓", kangxi: 13 },
  "楓": { char: "楓", simplified: 13, traditional: 13, kangxi: 13 },
  "芸": { char: "芸", simplified: 7, traditional: 12, traditionalChar: "蕓", kangxi: 12 },
  "蕓": { char: "蕓", simplified: 12, traditional: 12, kangxi: 12 },
  "菲": { char: "菲", simplified: 11, traditional: 11, kangxi: 11 },
  "寒": { char: "寒", simplified: 12, traditional: 12, kangxi: 12 },
  "亚": { char: "亚", simplified: 6, traditional: 8, traditionalChar: "亞", kangxi: 8 },
  "亞": { char: "亞", simplified: 8, traditional: 8, kangxi: 8 },
  "宜": { char: "宜", simplified: 8, traditional: 8, kangxi: 8 },
  "可": { char: "可", simplified: 5, traditional: 5, kangxi: 5 },
  "影": { char: "影", simplified: 15, traditional: 15, kangxi: 15 },
  "荔": { char: "荔", simplified: 9, traditional: 12, traditionalChar: "荔", kangxi: 12 },
  "枝": { char: "枝", simplified: 8, traditional: 8, kangxi: 8 },
  "彤": { char: "彤", simplified: 7, traditional: 7, kangxi: 7 },
  "萱": { char: "萱", simplified: 12, traditional: 12, kangxi: 12 },
  "涵": { char: "涵", simplified: 11, traditional: 11, kangxi: 11 },
  "诗": { char: "诗", simplified: 8, traditional: 13, traditionalChar: "詩", kangxi: 13 },
  "詩": { char: "詩", simplified: 13, traditional: 13, kangxi: 13 },
  "雅": { char: "雅", simplified: 12, traditional: 12, kangxi: 12 },
  "雨": { char: "雨", simplified: 8, traditional: 8, kangxi: 8 },
  "晴": { char: "晴", simplified: 12, traditional: 12, kangxi: 12 },
  "依": { char: "依", simplified: 8, traditional: 8, kangxi: 8 },
  "语": { char: "语", simplified: 9, traditional: 14, traditionalChar: "語", kangxi: 14 },
  "語": { char: "語", simplified: 14, traditional: 14, kangxi: 14 },
  "芊": { char: "芊", simplified: 6, traditional: 6, kangxi: 6 },
  "沐": { char: "沐", simplified: 7, traditional: 7, kangxi: 7 },
  "汐": { char: "汐", simplified: 6, traditional: 6, kangxi: 6 },
  "妤": { char: "妤", simplified: 7, traditional: 7, kangxi: 7 },
  "玥": { char: "玥", simplified: 8, traditional: 8, kangxi: 8 },
  "歆": { char: "歆", simplified: 13, traditional: 13, kangxi: 13 },
  "梓": { char: "梓", simplified: 11, traditional: 11, kangxi: 11 },
  "桐": { char: "桐", simplified: 10, traditional: 10, kangxi: 10 },
  "芷": { char: "芷", simplified: 7, traditional: 7, kangxi: 7 },
  "洛": { char: "洛", simplified: 9, traditional: 9, kangxi: 9 },
  "知": { char: "知", simplified: 8, traditional: 8, kangxi: 8 },
  "晚": { char: "晚", simplified: 11, traditional: 11, kangxi: 11 },
  "棠": { char: "棠", simplified: 12, traditional: 12, kangxi: 12 },
  "曼": { char: "曼", simplified: 11, traditional: 11, kangxi: 11 },
  "念": { char: "念", simplified: 8, traditional: 8, kangxi: 8 },
  "禾": { char: "禾", simplified: 5, traditional: 5, kangxi: 5 },
  "初": { char: "初", simplified: 7, traditional: 7, kangxi: 7 },
  "音": { char: "音", simplified: 9, traditional: 9, kangxi: 9 },
  "南": { char: "南", simplified: 9, traditional: 9, kangxi: 9 },
  "栀": { char: "栀", simplified: 9, traditional: 9, kangxi: 9 },
  "婧": { char: "婧", simplified: 11, traditional: 11, kangxi: 11 },
  "曦": { char: "曦", simplified: 20, traditional: 20, kangxi: 20 },
  "璇": { char: "璇", simplified: 15, traditional: 15, kangxi: 15 },
  "姝": { char: "姝", simplified: 9, traditional: 9, kangxi: 9 },
  "嫣": { char: "嫣", simplified: 14, traditional: 14, kangxi: 14 },
  "溪": { char: "溪", simplified: 13, traditional: 13, kangxi: 13 },
  "绮": { char: "绮", simplified: 11, traditional: 14, traditionalChar: "綺", kangxi: 14 },
  "綺": { char: "綺", simplified: 14, traditional: 14, kangxi: 14 },
  "悠": { char: "悠", simplified: 11, traditional: 11, kangxi: 11 },
  "昕": { char: "昕", simplified: 8, traditional: 8, kangxi: 8 },
  "楚": { char: "楚", simplified: 13, traditional: 13, kangxi: 13 },
  "予": { char: "予", simplified: 4, traditional: 4, kangxi: 4 },
  "寻": { char: "寻", simplified: 6, traditional: 12, traditionalChar: "尋", kangxi: 12 },
  "尋": { char: "尋", simplified: 12, traditional: 12, kangxi: 12 },
  "灵": { char: "灵", simplified: 5, traditional: 24, traditionalChar: "靈", kangxi: 24 },
  "靈": { char: "靈", simplified: 24, traditional: 24, kangxi: 24 },
};

export const STROKE_BULK_COUNT = 935;
